import json
import socket
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from pprint import pformat

import requests
from ipwhois import IPWhois

from pcap_toolkit.common import is_ipv4


def load_data(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def enrich_ip(ip, timeout=6):
    info = {"ip": ip}

    try:
        info["reverse_dns"] = socket.gethostbyaddr(ip)[0]
    except Exception:
        info["reverse_dns"] = None

    try:
        response = requests.get(f"http://ip-api.com/json/{ip}", timeout=timeout)
        info["ip_api"] = response.json()
    except Exception as exc:
        info["ip_api"] = {"error": str(exc)}

    try:
        lookup = IPWhois(ip).lookup_rdap(depth=0)
        info["rdap"] = {
            "asn": lookup.get("asn"),
            "asn_cidr": lookup.get("asn_cidr"),
            "asn_country_code": lookup.get("asn_country_code"),
            "network": lookup.get("network", {}).get("name") if lookup.get("network") else None,
        }
    except Exception as exc:
        info["rdap"] = {"error": str(exc)}

    return ip, info


def export_lua_ioc_table(slds, ips, out_path):
    out_file = Path(out_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    with open(out_file, "w", encoding="utf-8") as handle:
        handle.write("-- Auto-generated by pcap_toolkit.enrichment\n")
        handle.write("local generated = {}\n")

        handle.write("generated.slds = {\n")
        for sld in sorted(slds):
            handle.write(f'    ["{sld}"] = true,\n')
        handle.write("}\n\n")

        handle.write("generated.c2_ips = {\n")
        for ip in sorted(ips):
            handle.write(f'    ["{ip}"] = true,\n')
        handle.write("}\n\nreturn generated\n")

    return str(out_file)


def build_markdown_report(results):
    lines = []
    lines.append("# PCAP Analysis Report")
    lines.append("")
    lines.append("## Questions")
    lines.append("")
    lines.append("**1. What is a Domain Generation Algorithm (DGA)?**")
    lines.append("")
    lines.append(
        "A Domain Generation Algorithm (DGA) is an algorithm used by malware to deterministically produce a large set of domain names, often pseudo-random, so the malware can attempt to contact command-and-control (C2) infrastructure at those domains. Attackers only register a subset of generated names, making blocking and takedown harder."
    )
    lines.append("")
    lines.append("**2a. What exists/occurs in the provided pcap?**")
    lines.append("")
    lines.append("- Packets total: {}".format(results["pcap_summary"].get("packets_total")))
    lines.append("- DNS queries observed: {}".format(results["pcap_summary"].get("dns_count")))
    lines.append(
        "- Observed DNS queries include multiple long, high-entropy subdomains (examples in timeline). Many of these resolved to external IPs in the capture."
    )
    lines.append("")
    lines.append("**2b. Is the file related to information security?**")
    lines.append("")
    lines.append(
        "Yes. The capture shows DNS behavior consistent with DGA-based C2 resolution: multiple algorithmically-looking subdomains (high entropy), several different names resolving to the same external IP, and short beacon-like timing between queries. This pattern is typical for malware beaconing and warrants further investigation."
    )
    lines.append("")
    lines.append("## Enrichment Results (per IP)")
    lines.append("")

    for ip, info in results["ips"].items():
        lines.append(f"### {ip}")
        lines.append(f'- Reverse DNS: {info.get("reverse_dns") or "(none)"}')

        ip_api = info.get("ip_api", {})
        if ip_api.get("error"):
            lines.append(f'- Geo/IP lookup error: {ip_api.get("error")}')
        else:
            lines.append(
                f'- Country: {ip_api.get("country")}, Region: {ip_api.get("regionName")}, City: {ip_api.get("city")}, ISP: {ip_api.get("isp")}, Org: {ip_api.get("org")}, AS: {ip_api.get("as")}'
            )

        rdap = info.get("rdap")
        if rdap and not rdap.get("error"):
            lines.append(
                f'- ASN: {rdap.get("asn")}, ASN country: {rdap.get("asn_country_code")}, Network: {rdap.get("network")}'
            )
        else:
            lines.append(f'- RDAP lookup: {rdap.get("error") if rdap else "(none)"}')

        lines.append("")

    lines.append("## Timeline (per internal source IP)")
    for src, entries in results["timeline"].items():
        lines.append(f"### {src}")
        for entry in entries:
            lines.append(
                f'- {entry.get("time")}: {entry.get("qname")} -> answers: {pformat(entry.get("answers"))}'
            )
        lines.append("")

    lines.append("## Original file")
    lines.append(
        "Google Drive link: https://drive.google.com/file/d/1jad6drgd4gO7uG2F7nZmWy7vICGJhtEV/view?usp=sharing"
    )

    return "\n".join(lines)


def run_ip_enrichment(in_json, out_json=None, out_md=None, max_workers=8, timeout=6):
    data = load_data(in_json)

    ips = set()
    for rec in data.get("dns", []):
        for answer in rec.get("answers", []):
            rdata = answer.get("rdata")
            if rdata and is_ipv4(rdata):
                ips.add(rdata)

    enrich = {}
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(enrich_ip, ip, timeout): ip for ip in sorted(ips)}
        for future in as_completed(futures):
            ip = futures[future]
            try:
                enriched_ip, info = future.result()
                enrich[enriched_ip] = info
            except Exception as exc:
                enrich[ip] = {
                    "ip": ip,
                    "reverse_dns": None,
                    "ip_api": {"error": str(exc)},
                    "rdap": {"error": str(exc)},
                }

    timeline = {}
    for rec in data.get("dns", []):
        src = rec.get("src") or "unknown"
        timeline.setdefault(src, []).append(
            {
                "time": rec.get("time"),
                "qname": rec.get("qname"),
                "answers": rec.get("answers"),
            }
        )

    results = {
        "ips": enrich,
        "timeline": timeline,
        "pcap_summary": {
            "packets_total": data.get("packets_total"),
            "dns_count": len(data.get("dns", [])),
        },
    }

    if out_json:
        Path(out_json).parent.mkdir(parents=True, exist_ok=True)
        with open(out_json, "w", encoding="utf-8") as handle:
            json.dump(results, handle, indent=2, ensure_ascii=False)

    if out_md:
        Path(out_md).parent.mkdir(parents=True, exist_ok=True)
        with open(out_md, "w", encoding="utf-8") as handle:
            handle.write(build_markdown_report(results))

    return results
